### ISSUE TITLE
[詞庫問題回報] 孿錯誤讀音

### ISSUE THREAD

**Issue by Libero-zz** [OpenVanilla/McBopomofo#379]
**分類**

- [ o] 錯字或錯誤讀音
- [ ] 缺字/詞
- [ ] 其他

**說明**
請說明是哪個字寫錯或是標音錯誤，以及正確的寫法與念法。

「孿」生兄弟的「孿」應是[ㄌㄨㄢˊ ]而非[ㄌㄩㄢˊ ]

**相關資料**
像是字典的連結等。

https://dict.concised.moe.edu.tw/dictView.jsp?ID=15513&la=0&powerMode=0
https://dict.revised.moe.edu.tw/dictView.jsp?ID=66787&la=0&powerMode=0

**Comment by tianjianjiang** [comment]
@Libero-zz @lukhnos @mjhsieh Before 1988, this character and the ones with similar glyphs are all /ㄌㄩㄢˊ/ instead of /ㄌㄨㄢˊ/. I recommend not removing /ㄌㄩㄢˊ/.

BTW, the actual revision of the MOE dictionary happened much later than 1988:
https://zh-tw.facebook.com/254175541296639/posts/1025038124210373/
> 5. 【攣】
「國語一字多音審訂表｣
88年〔ㄌㄨㄢˊ〕
〔ㄌㄩㄢˊ〕較難發音，且「孿」亦取〔ㄌㄨㄢˊ〕，
依今日口語及大陸資料取〔ㄌㄨㄢˊ〕。
101年12月12日公布「國語一字多音審訂表（初稿）」
101年〔ㄌㄨㄢˊ〕：痙攣、拘攣
〔ㄌㄩㄢˊ〕〔ㄌㄧㄢˋ〕併讀為〔ㄌㄨㄢˊ〕。
網路版《教育部重編國語辭典修訂本》
【痙攣】
注音
ㄐㄧㄥˋ　ㄌㄩㄢˊ

**Comment by lukhnos** [comment]
> I recommend not removing /ㄌㄩㄢˊ/.

[PR #380](https://github.com/openvanilla/McBopomofo/pull/380) 裡面的單字保留了ㄌㄩㄢˊ的讀音。關於字的讀音，我的原則是把 xcin 的 bpmf.cin 當作是固定不變的資料，任何新增的讀音或是非 Big5 原有的字，要不就照 bpmf-ext.cin 的順序，要不就是在 bpmf.cin 原有的資料後面添增。PR 中的ㄌㄨㄢˊ是這樣加入的。

@tianjianjiang 所以值得討論的是，派生詞要不要保留？聽起來你的建議是保留原來的讀音（例如ㄌㄩㄢˊ ㄕㄥ），但是加上口語習慣讀音。是這樣嗎？

**Comment by tianjianjiang** [comment]
> > I recommend not removing /ㄌㄩㄢˊ/.
> 
> [PR #380](https://github.com/openvanilla/McBopomofo/pull/380) 裡面的單字保留了ㄌㄩㄢˊ的讀音。關於字的讀音，我的原則是把 xcin 的 bpmf.cin 當作是固定不變的資料，任何新增的讀音或是非 Big5 原有的字，要不就照 bpmf-ext.cin 的順序，要不就是在 bpmf.cin 原有的資料後面添增。PR 中的ㄌㄨㄢˊ是這樣加入的。
> 
> @tianjianjiang 所以值得討論的是，派生詞要不要保留？聽起來你的建議是保留原來的讀音（例如ㄌㄩㄢˊ ㄕㄥ），但是加上口語習慣讀音。是這樣嗎？

是的。這個音節有點特別，除了形似的這兩三個字之外，就我所知沒有其他的字這麼念。保留舊讀音給派生詞的好處是，如果 bpmf 固定資料裡還會有這個音節，那麼 BPMFMapping 裡的派生詞可以確保這個音總是 morpheme bouned phoneme. 否則有個小小的可能性是用 /ㄌㄩㄢˊ/ 會得到「孿甥兒」。

**Comment by lukhnos** [comment]
> 保留舊讀音給派生詞的好處是，如果 bpmf 固定資料裡還會有這個音節，那麼 BPMFMapping 裡的派生詞可以確保這個音總是 morpheme bouned phoneme. 

有道理。我把 PR 裡拿掉ㄌㄩㄢˊ派生詞的部分移除了，PTAL.

**Comment by tianjianjiang** [comment]
> > 保留舊讀音給派生詞的好處是，如果 bpmf 固定資料裡還會有這個音節，那麼 BPMFMapping 裡的派生詞可以確保這個音總是 morpheme bouned phoneme.
> 
> 有道理。我把 PR 裡拿掉ㄌㄩㄢˊ派生詞的部分移除了，PTAL.

Thank you!
