### ISSUE TITLE
切換輸入法時沒有反應，無法切換 -- How to restart Plain Bopomofo ?

### ISSUE THREAD

**Issue by benpptung** [openvanilla/McBopomofo#83]
It happened occasionally.
How can I restart Plain Bopomofo from command line?
So I don't need to restart Mac just because I cannot switch Input method to Plain Bopomofo. 

Thanks a lot!! :)

**Comment by ShikiSuen** [comment]
@benpptung 

1. Please retest the issue using the latest source code commited to the master branch in this repo. // Requiring >30GB download of Xcode. Zonble recently finished rewriting of some modules using Swift in order to suppress some possible ObjC issues which are hardly detectable by LLVM.

2. ㄅ半 in McBopomofo is somehow meaningless, I'm afraid. Most ㄅ半 users have their fingers muscle-trained during their years of using Windows 3.0 - 95 and Windows NT 3.51. Windows NT 4 and Windows 98 started shipping Microsoft New Phonetic IME, representing the modern combo Daqian / 01 / Wang / Microsoft bopomofo IME style (actually, Matsushita Hanin IME did this earlier). However, ㄅ半 has limited characters support and fixed candidate sequence. Can you really sure any other non-Microsoft ㄅ半-like IMEs can give you exactly the same candidate listing sequences? If you really need ㄅ半 on macOS, I am afraid that you might want to convert the Win95 ㄅ半 ime's table to the data format which McBopomofo's PlainBopomofo mode can read (or a cin file readable by OpenVanilla main app). Candidate listing sequences are why you people choose ㄅ半. // I dunno the situation regarding the ㄅ半 in Windows XP after applying the Traditional Chinese EXT-B support package since the download of the patch gets removed by Microsoft.

**Comment by zonble** [comment]
@ShikiSuen Please respect the habits of the others. If you don't use something, it does not mean it is also useless for others.

**Comment by ShikiSuen** [comment]
@zonble Good to see this grabs your attention.
I assume you want this feature to be kept, then I guess this is a good change to discuss how to make this feature as authentic as what feels like the ㄅ半 on Win9x.

The essence of providing an authentic ㄅ半 experience to the end user is to make sure the sequences of candidate lists are as same as those used in the Win9x ㄅ半. I have tried searching on Google to see whether there's a tool for converting the "WINIME.IME" (from Windows 3.x) to CIN, but I found no usable results. Some volunteers provided their customized ㄅ半 cin files, including the one used in PIME. However, there's no way to guarantee its authenticity comparing to the the list presented in WINIME.IME file.

Meanwhile, the data-plain-bpmf.txt used in the current Plain mode of the McBopomofo is simply a derived copy of data.txt with the removal of frequency data and phrases data (for words not less than 2 kanji chars).

Let me leave the WINIME.IME file (extracted from Windows 3.1) here. It will be greatly helpful if someone can reverse-engineer it: [WINIME.IME.zip](https://github.com/openvanilla/McBopomofo/files/7867993/WINIME.IME.zip)

![image](https://user-images.githubusercontent.com/3164826/150818176-06ba7181-c517-45ac-ba82-10089906e0f0.png)
